# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:23
from __future__ import unicode_literals

import auction.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Banned'), (2, 'Adjudicated')], default=0)),
                ('seller', models.CharField(max_length=150, verbose_name='Seller')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('item_description', models.CharField(max_length=1000, verbose_name='Item description')),
                ('price', auction.models.PositiveDecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Minimum price (€)')),
                ('bidder_pk_string', models.CharField(max_length=2000)),
                ('last_bidder', models.CharField(max_length=150)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2017, 10, 20, 19, 23, 39, 369249))),
                ('locked_by', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('sv', 'Swedish')], default='en', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=150)),
                ('amount', auction.models.PositiveDecimalField(decimal_places=2, default=0, max_digits=15)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Auction')),
            ],
        ),
    ]
